NumPy is a Python library.

NumPy is used for working with arrays.

NumPy is short for "Numerical Python".

In [3]:
import numpy as np

##Create a 0D Array

In [8]:
 

arr=np.array([10])
print(arr)
print('number of dimention is:',arr.ndim)

[10]
number of dimention is: 1


##Create a 1D Array

In [3]:
arr1=np.array([1,3,5,7,9])
print(arr1)
print("number of dimension:",arr1.ndim)         

[1 3 5 7 9]
number of dimension: 1


##Create a 2D Array

In [4]:
arr2=np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)
print("number of dimension:",arr2.ndim)

[[1 2 3 4]
 [5 6 7 8]]
number of dimension: 2


##Create a 3D Array

In [5]:
arr3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr3)
print("number of dimension:",arr3.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
number of dimension: 3


In [6]:
arr4=np.array([[1,2,3],[4,5,6],[7,8,9]],ndmin=3)
print(arr4)
print("number of dimension:",arr4.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
number of dimension: 3


In [7]:

import numpy as np
arr1 = np.array([[1, 2],
                 [3, 4]])

arr2 = np.array([[5, 6],
                 [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)
print(arr.shape)

[[1 2 5 6]
 [3 4 7 8]]
(2, 4)
